run:
  timeout: 5m
  modules-download-mode: readonly
  skip-dirs:
    - test/mocks

linters:
  enable:
    - gofmt
    - govet
    - goimports
    - gosimple
    - staticcheck
    - errcheck
    - ineffassign
    - typecheck
    - goconst
    - gosec
    - unconvert
    - gocritic
    - revive
    - whitespace

linters-settings:
  goimports:
    local-prefixes: monitor
  goconst:
    min-len: 2
    min-occurrences: 3
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
  revive:
    rules:
      - name: exported
        arguments:
          - disableStutteringCheck
  gosec:
    excludes:
      - G404  # Use of weak random number generator

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gosec
        - errcheck
    - path: internal/mocks/.*
      linters:
        - gosec
        - errcheck
        - revive
  max-issues-per-linter: 0
  max-same-issues: 0

output:
  format: colored-line-number
  print-issued-lines: true
  print-linter-name: true 