server:
  port: 8080
  mode: debug

database:
  driver: mysql
  host: localhost
  port: 3306
  username: root
  password: root
  dbname: monitor
  charset: utf8mb4
  parseTime: true
  loc: Local

log:
  level: debug
  filename: ./logs/monitor.log
  maxSize: 100
  maxBackups: 10
  maxAge: 30
  compress: false 